spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/usersLck/ck-cloud
            search-paths: /conf
        label:  master
server:
  port: 8801